/* click constants */
export const CLICKS_SAVED = 'CLICKS_SAVED';
export const CLICKER_HAS_CHANGED = 'CLICKER_HAS_CHANGED';
export const CLICKER_CHANGES_CLEARED = 'CLICKER_CHANGES_CLEARED';

/* save callbacks */
export const SAVE_CALLBACK_REGISTERED = 'SAVE_CALLBACK_REGISTERED';
export const SAVE_CALLBACK_DEREGISTERED = 'SAVE_CALLBACK_DEREGISTERED';